spring:
  application:
    name: smart-auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 10
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:smart.IOT@yunctiys52_redis}
    pool:
      max-active: 20
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/yx-ag_auth?useUnicode=true&characterEncoding=UTF8
    username: root
    password: smart.IOT@yunctiys52
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: admin
    password: admin@yuncitys.com
  zipkin:
    enabled: true
  sleuth:
    sampler:
      percentage: 1
mybatis:
  basepackage: com.yuncitys.smart.security.auth.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: 9777 #启动端口

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
    prefer-ip-address: true
    ip-address: localhost
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # docker 部署开启,记得将IP修改为部署所在服务器的外网IP
      #defaultZone: http://${EUREKA_HOST:106.52.177.26}:${EUREKA_PORT:8761}/eureka/

jwt:
  token-header: Authorization
  expire: 3600
  rsa-secret: xx1WET12^%3^(WE45
  user-service: smart-admin

client:
  id: smart-auth
  secret: 123456
  token-header: client-token
  expire: 3600
  rsa-secret: x2318^^(*WRYQWR(QW&T

redis:
  aec-key: xx288&^^%$!@#4dc
  aec-iv: 0123456789abcdef

# 配置swagger
swagger:
  enabled: true
  base-package: com.yuncitys.smart.security.auth
  title: smart-auth
  version: 1.0.0.SNAPSHOT
  description: 鉴权服务
  contact:
    name: auth

mapper:
  mappers: com.yuncitys.smart.security.common.mapper.CommonMapper


logging:
  level:
    root: info
    ## 这里设置为info，是因为如果不设置，debug时会不断打印mq日志。
    org.springframework.integration.endpoint.SourcePollingChannelAdapter: info
#    org.springframework.security: DEBUG
